// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7t0uVA2OrPiUVhZNL5dW1cs7_1hxxzUc',
    appId: '1:829048327348:web:198d4f49ce710472a69be1',
    messagingSenderId: '829048327348',
    projectId: 'rentalproperty-ea845',
    authDomain: 'rentalproperty-ea845.firebaseapp.com',
    storageBucket: 'rentalproperty-ea845.appspot.com',
    measurementId: 'G-PLSBFWPPFJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHyZYN8Aq39ybQ2sec2UyiYnVx6dOw1wI',
    appId: '1:829048327348:ios:4282fa7dd32589bca69be1',
    messagingSenderId: '829048327348',
    projectId: 'rentalproperty-ea845',
    storageBucket: 'rentalproperty-ea845.appspot.com',
    iosBundleId: 'com.example.rentalProperty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHyZYN8Aq39ybQ2sec2UyiYnVx6dOw1wI',
    appId: '1:829048327348:ios:4282fa7dd32589bca69be1',
    messagingSenderId: '829048327348',
    projectId: 'rentalproperty-ea845',
    storageBucket: 'rentalproperty-ea845.appspot.com',
    iosBundleId: 'com.example.rentalProperty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7t0uVA2OrPiUVhZNL5dW1cs7_1hxxzUc',
    appId: '1:829048327348:web:6f95fe85fc8e7487a69be1',
    messagingSenderId: '829048327348',
    projectId: 'rentalproperty-ea845',
    authDomain: 'rentalproperty-ea845.firebaseapp.com',
    storageBucket: 'rentalproperty-ea845.appspot.com',
    measurementId: 'G-F60K288TGJ',
  );
}
